[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run postbuild && npm start"
healthcheckPath = "/api/v1/monitoring/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
