[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npx prisma migrate deploy && npx ts-node prisma/seed.ts"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
